# Licenses_exporter config file
---
licenses:
  - name: MATLAB R2018b
    type: lmutil
    license_server: 27000@windhcp1.uco.es
    features_to_include: MATLAB,SIMULINK,Audio_System_Toolbox,Control_Toolbox,Signal_Blocks,Neural_Network_Toolbox,GADS_Toolbox,Image_Toolbox,Optimization_Toolbox,PDE_Toolbox,Signal_Toolbox,Statistics_Toolbox,Symbolic_Toolbox,Identification_Toolbox
    monitor_users: True
    monitor_reservations: False
  - name: MATLAB R2014-R2015
    type: lmutil
    license_server: 27000@windhcp2.uco.es
    features_to_include: MATLAB,Image_Toolbox,PDE_Toolbox,Symbolic_Toolbox
    monitor_users: True
    monitor_reservations: False
  - name: MATHCAD
    type: lmutil
    license_server: 7788@windhcp1.uco.es
    features_to_include: MATHCAD,254,255,256,257
    monitor_users: True
    monitor_reservations: False
  - name: AUTOCAD2017
    type: lmutil
    license_server: 27001@windhcp1.uco.es
    features_to_include: 86604ACD_2017_0F
    monitor_users: True
    monitor_reservations: False
  - name: ORIGIN2018
    type: lmutil
    license_server: 27002@windhcp1.uco.es
    features_to_include: OriginPro
    monitor_users: True
    monitor_reservations: False
  - name: ANSYS
    type: lmutil
    license_server: 1055@ucoad03.uco.es
    features_to_include: aa_ds,aa_mcad,aa_t_me,aim_mp1,aa_r_me
    monitor_users: True
    monitor_reservations: False
  - name: SPSS
    type: lsmon
    license_server: windhcp2.uco.es
    features_to_include: 1200
    monitor_users: True
    monitor_reservations: False
  - name: GRAPHER
    type: lsmon
    license_server: windhcp2.uco.es
    features_to_include: Grapher
    monitor_users: True
    monitor_reservations: False
config:
  port: 8000
  sleep: 5
  lsmon_cmd: ./lsmon
  lmutil_cmd: ./lmutil lmstat -a -c
